services:
  deno:
    #user: ${UID}:${GID}
    build: ./docker
    image: deno_exploration
    restart: always
    container_name: exploration_deno_app
    volumes:
      - ./app/:/app
    ports:
      - 3002:3000
      - 5173:5173
    expose:
      - 3000
      - 5173
    tty: true
    command:
      - /bin/bash
      - -c
      - |
        cd chess_frontend/
        deno task dev --host